
version: "3.3"
  
services:

  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4000-4002:4000-4002"
    environment:
      SERVICES: "sqs:4000,s3:4001,sns:4002"
      DEBUG: 1

  transcoder:
    image: bleckfisk/audiotranscoder
    build:
      context: .
      args:
        PIPENV_ARGS: "--dev"
    depends_on:
      - localstack