
version: "3.3"
  
services:

  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "5000-5002:5000-5002"
    environment:
      SERVICES: "sqs:5000,s3:5001,sns:5002"
      DEBUG: 1

  transcoder:
    image: bleckfisk/audiotranscoder
    build:
      context: .
      args:
        PIPENV_ARGS: "--dev"
    depends_on:
      - localstack