
AWS_SQS_ENDPOINT_URL = "http://localstack:5000/"
AWS_SQS_QUEUE_NAME = "testqueue"
AWS_S3_ENDPOINT_URL = "http://localstack:5001/"
AWS_SNS_ENDPOINT_URL = "http://localstack:5002/"
AWS_SNS_TOPIC = "testtopic"
AWS_DEFAULT_REGION = "eu-west-1"
AWS_ACCESS_KEY_ID = "test"
AWS_SECRET_ACCESS_KEY = "test"
BUCKET_NAME = "testbucket"
